name: "Distribution support request"
description: "Request a new distribution"
title: "[Distribution]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        You may request a distribution that is not present in `proot-distro list`. Please note that non-standard distributions like "Gentoo Prefix" as well as distributions that assist hacking will be rejected.
  - type: textarea
    attributes:
      label: Description
      description: Tell us why this distribution should be added into PRoot-Distro support list. How it is different from already added ones such as Arch Linux or Debian? Pay attention that PRoot-Distro includes distributions only in the minimal configuration. You'll get a bare command line which mostly looks like same across all present distributions. All "fancy" configurations are discarded during rootfs packaging process.
  - type: input
    attributes:
      label: Home page URL
    validations:
      required: true
  - type: input
    attributes:
      label: Root file system archive URL
  - type: checkboxes
    attributes:
      label: Does 64bit ARM builds available (arm64, aarch64)?
      description: Distributions not supporting at least 64 bit ARM platforms are not eligible to be included. No exceptions here.
      options:
        - label: Yes, distribution provides 64 bit images.
          required: true
